### ISSUE TITLE
Dynbalance

### ISSUE THREAD

**Issue by Anderson321** [christianrauch/msp#7] opened 2017-05-18 21:14 UTC
Hey so I can't send RC commands but I can set motor values because I dont have DYNBALANCE included. Since I am using cleanfliht and not MultiWii code, where should i comment out "#define DYNBALANCE" in Multiwii's config.h?

thanks

**Comment by Anderson321** [comment] 2017-05-18 21:59
Where do I *comment* out DYNBALANCE

correction

**Comment by christianrauch** [comment] 2017-05-18 22:01
Have you enabled the `RX_MSP` feature? When you type `feature` in the cleanflight/baseflight CLI, it should print a list that contains `RX_MSP`. Otherwise you need to select the receiver type (PPM, PWM, SBUS, MSP) in the configuration tab.

**Comment by Anderson321** [comment] 2017-05-18 22:12
Right now, I want to configure cleanflight for RX_PPM, control it with a RC and then have the raspberry pi take over and in your code in fcu_arm_test.cpp:
You enable RX_MSP automatically so that shouldn't be a problem.
    // on cleanflight, we need to enable the "RX_MSP" feature
    if(fcu.isFirmwareCleanflight()) {
        if(fcu.enableRxMSP()==1) {
            std::cout<<"RX_MSP enabled, restart"<<std::endl;
            feature_changed = true;
            goto start;
        }

I am able to setMotors perfectly fine but I can't send RC commands, which I think is the DYNBALANCE thing, right?

**Comment by Anderson321** [comment] 2017-05-18 22:34
Ok so update: I put in

if(fcu.isFirmwareCleanflight()) {
if(fcu.enableRxMSP()==1) {
std::cout<<"RX_MSP enabled, restart"<<std::endl;
feature_changed = true;
goto start;
}

to enable RX_MSP and then after that I am doing:

fcu.setRc(1500,1500,1500,1500,1500,0,0,0);
std::this_thread::sleep_for(std::chrono::milliseconds(3000));

My AUX 1 channel after 1500 is to arm the FC and then the 4 other channels should be throttle pitch yaw roll etc. Nothing is happening though. Thanks for your time

**Comment by christianrauch** [comment] 2017-05-18 22:47
`#define DYNBALANCE` is related to the original MultiWii firmware for Arduino / 8bit AVR microcontroller. I would recommend to select `RX_MSP` in the GUI or CLI beforehand since it requires to reboot the FC to apply the new settings.

Can you confirm that you have `RX_MSP` enabled and that the virtual control sticks in the Receiver tab of the Cleanflight GUI allow you to change the channels and arm / disarm the FC?

**Comment by Anderson321** [comment] 2017-05-18 23:13
I have RX_MSP enabled but the virtual sticks aren't working, I even have my AUX 1 at 1500 (which is arming it)... Scratch that, the motors started after awhile with the virtual control sticks... but now doesn't start up again. It's very inconsistent.

Also, I went into FCU.arm() and I changed it to this so it would work for my arming configuration:

const uint16_t aux1= arm ? 1500 : 1000;

return setRC(1000, 1000, 1000, 1000, aux1, 1000, 1000, 1000);
I've debugged it and it's getting caught in an infinite loop in FCU.arm_block()  where it goes into arm(), trying to setRC to (1000, 1000, 1000, 1000, aux1, 1000, 1000, 1000) where aux1 is 1500.

**Comment by christianrauch** [comment] 2017-05-18 23:26
Can you check if arming works if you switch the channel map in the Receiver tab? It might be possible that only one of them (either `AETR1234` or `TAER1234`) is working. It should always be possible to arm via the stick combo.

**Comment by Anderson321** [comment] 2017-05-18 23:33
Yeah, it's very inconsistent for each stick combo...

**Comment by christianrauch** [comment] 2017-05-18 23:57
Is `FlightController::arm()` arming when you switch to `AETR1234`?

**Comment by Anderson321** [comment] 2017-05-19 00:16
It doesn't arm in either configuration.

**Comment by Anderson321** [comment] 2017-05-19 00:22
I have debugged it and during arm it enters the FlightController::setRC command with the parameter (1000, 1000, 1000, 1000, 1500, 1000, 1000, 1000) but nothing happens. RX_MSP is enabled as well

**Comment by christianrauch** [comment] 2017-05-19 08:47
Can you provide a link from the [Cleanflight release page](https://github.com/cleanflight/cleanflight/releases) to the exact Cleanflight version (cleanflight_*_NAZE.hex) that you are using? Can you also upload a dump of your configuration (type `dump` in the CLI)?

I will try to reproduce your setup and see if I encounter the same issues you are.

**Comment by Anderson321** [comment] 2017-05-19 21:48
https://github.com/cleanflight/cleanflight/tree/v1.11.0/docs I'm using 1.11 


# version
# Cleanflight/NAZE 1.11.0 Nov 28 2015 / 15:30:06 (0c82a7b)
# dump master

# mixer
mixer QUADX
mmix reset
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature FAILSAFE
feature TELEMETRY
feature RX_MSP
feature ONESHOT125


# map
map AETR1234


# serial
serial 0 1 115200 57600 0 115200
serial 1 0 115200 57600 0 115200


# led
led 0 15,15:ES:IA:0
led 1 15,8:E:WF:0
led 2 15,7:E:WF:0
led 3 15,0:NE:IA:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:IA:0
led 7 0,7:W:WF:0
led 8 0,8:W:WF:0
led 9 0,15:SW:IA:0
led 10 7,15:S:WF:0
led 11 8,15:S:WF:0
led 12 7,7:U:WF:0
led 13 8,7:U:WF:0
led 14 7,8:D:WF:0
led 15 8,8:D:WF:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0:::0
led 29 0,0:::0
led 30 0,0:::0
led 31 0,0:::0


# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

set looptime = 1000
set emf_avoidance = OFF
set i2c_overclock = OFF
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = ON
set input_filtering_mode = OFF
set min_throttle = 1200
set max_throttle = 2000
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set retarded_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set fixedwing_althold_dir = 1
set reboot_character = 82
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_auto_config = ON
set gps_auto_baud = OFF
set serialrx_provider = SPEK1024
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = OFF
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set max_angle_inclination = 500
set gyro_lpf = 42
set moron_threshold = 32
set gyro_cmpf_factor = 600
set gyro_cmpfm_factor = 250
set yaw_control_direction = 1
set pid_at_min_throttle = ON
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set rx_min_usec = 885
set rx_max_usec = 2115
set acc_hardware = 0
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0

# rxfail
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile
profile 0

# aux
aux 0 0 0 1300 1700
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo
servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83
set gps_wp_radius = 200
set nav_controls_heading = ON
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 0
set yaw_deadband = 0
set throttle_correction_value = 0
set throttle_correction_angle = 800
set default_rate_profile = 0
set gimbal_mode = NORMAL
set acc_lpf_factor = 4
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff =  5.000
set acc_unarmedcal = ON
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf =  0.600
set baro_cf_vel =  0.985
set baro_cf_alt =  0.965
set mag_declination = 0
set pid_controller = MWREWRITE
set p_pitch = 165
set i_pitch = 50
set d_pitch = 5
set p_roll = 100
set i_roll = 65
set d_roll = 5
set p_yaw = 115
set i_yaw = 50
set d_yaw = 0
set p_pitchf =  1.400
set i_pitchf =  0.400
set d_pitchf =  0.030
set p_rollf =  1.400
set i_rollf =  0.400
set d_rollf =  0.030
set p_yawf =  3.500
set i_yawf =  0.400
set d_yawf =  0.010
set yaw_p_limit = 500
set level_horizon =  3.000
set level_angle =  5.000
set sensitivity_horizon = 75
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 90
set i_level = 10
set d_level = 100
set p_vel = 120
set i_vel = 45
set d_vel = 1
set dterm_cut_hz = 0
set pterm_cut_hz = 0
set gyro_cut_hz = 0

# dump rates

# rateprofile
rateprofile 0

set rc_rate = 90
set rc_expo = 65
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_rate = 0
set pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500


Thank you for your help I appreciate it

**Comment by Anderson321** [comment] 2017-05-19 22:09
I am using a rev5 naze btw

**Comment by christianrauch** [comment] 2017-05-20 13:23
I can confirm that arming is working with Cleanflight version 1.14.2.
Beginning with version 2.0, `MSP_SET_RAW_RC` messages are ignored for some targets, e.g. for the NAZE. You will recognise this, if the `MSP_RC` message is empty (e.g. run `fcu_test` and check "Rc channels" is 0).

The solution to this problem is to either stick with version 1.14.2 or to recompile your own Cleanflight version 2. In the latter case, you need to add `#define USE_RX_MSP` to the `target.h`.

For example, I am maintaining my own betaflight version for NAZE32 rev6 targets that removes sensors that are not present and adds `USE_RX_MSP`: https://github.com/christianrauch/betaflight/tree/naze_rev6_full. You can have a look at how I patched file `src/main/target/NAZE/target.h` and apply similar changes to your target.

**Comment by Anderson321** [comment] 2017-05-20 20:31
Thank you! I will try this as soon as possible and let you know if it worked. Would your betaflight version work on rev5 or would i need rev6?

**Comment by Anderson321** [comment] 2017-05-22 02:26
So I switched to 1.14.2... I still cannot arm. I will try to arm and then I run fcu_test and none of the RC channels change. Also in cleanflight configurator I made it so all values of aux1 would arm the drone (and I made it so motors would spin when armed), but when i switch to RX MSP the motors don't spin. It's like AUX1 when switched over to MSP isn't arming the drone. Do you have any thoughts?

**Comment by christianrauch** [comment] 2017-05-22 08:33
`fcu_test` will not change the channels values, it only reads messages from the FC.

Have you updated to the newest version of the library? I recently fixed a bug related to the RX channel mapping.

**Comment by Anderson321** [comment] 2017-05-22 17:13
What I mean is that I try to arm it (I set aux to 1500) and then do fcu_test to see if the RC value changed after the fact. But the RC values are the same as before.  I updated to the newest version of the library.

Also. I tried arming it this morning, it armed. However, I'll try to arm it again and then it will get stuck in the arm_block() function.

**Comment by Anderson321** [comment] 2017-05-22 17:23
I will also run msp_read_test and my value of aux1 is 1500, which is confusing to me because that is in the range of being armed according to my configuration, but it doesn't think it is armed.

**Comment by Anderson321** [comment] 2017-05-22 17:32
I'm going to try flashing your betaflight firmware onto my Naze. I'm not sure how to flash your version locally. How do I do this?

**Comment by christianrauch** [comment] 2017-05-25 23:04
It is important to note that when controlling the FC via `MSP_SET_RAW_RC` messages, the FC is affected by the same failsafe rules that are applied to regular controls, e.g. via a PPM or PWM signal. That means that you need to provide new values for the channels at regular intervalls, e.g. at least every 1 second. If you do not provide new values within the failsafe guard time, the FC will go into failsafe mode and it will set default values for these channels. I guess, these are the values that you see when reading the `MSP_RC` message.

I recommend to write your own program that continuously provides channel values for the FC, e.g. from a joystick or keyboard. You can also have a look at ROS and the MultiWii ROS node (https://github.com/christianrauch/ros-multiwii) and use another ROS node to continuously provide commands.

If you are able to set channel values via the `MSP_SET_RAW_RC` message on cleanflight 1.14.2 please close this issue.

**Comment by Anderson321** [comment] 2017-05-26 02:10
I got it to arm! For some reason, I wasn't able to arm through aux 1, but I can arm by setting yaw to 2000 and throttle 1000, and the other two to 1500. Yeah I have noticed that I need to continuously update the channels. I was trying to just setRc and then sleeping for like 5 seconds but it stopped before the sleep was over. Is 1 second a good rule of thumb? Thanks

**Closed** 2017-05-26 02:10 UTC
